sudo: false
language: ruby
cache:
  yarn: true
  bundler: true
env:
  - NODE_VERSION=stable
  - NODE_VERSION=lts/*
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
before_install:
  - nvm install $NODE_VERSION
  - gem update --system
  - gem install bundler
before_script:
  - yarn install
script:
  - yarn run lint
  - bundle exec rubocop
  - bundle exec rake
