# frozen_string_literal: true

RSpec.describe Yarnlock do
  let(:yarnlock) do
    <<~YARNLOCK
      # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
      # yarn lockfile v1


      "@yarnpkg/lockfile@^1.0.0":
        version "1.0.0"
        resolved "https://registry.yarnpkg.com/@yarnpkg/lockfile/-/lockfile-1.0.0.tgz#33d1dbb659a23b81f87f048762b35a446172add3"
    YARNLOCK
  end
  let(:parsed_object) do
    {
      '@yarnpkg/lockfile@^1.0.0' => {
        'version' => '1.0.0',
        'resolved' => 'https://registry.yarnpkg.com/@yarnpkg/lockfile/-/lockfile-1.0.0.tgz#33d1dbb659a23b81f87f048762b35a446172add3'
      }
    }
  end

  describe '.parse' do
    context 'when invalid text was passed' do
      it { expect { Yarnlock.parse 'Invalid' }.to raise_error(/^Could not parse/) }
    end

    context 'when correct text was passed' do
      it 'parses correct string' do
        expect(Yarnlock.parse(yarnlock)).to eq parsed_object
      end
    end
  end

  describe '.load' do
    let(:file_path) { File.expand_path('fixture/yarn.lock', __dir__) }

    it 'can load actual file' do
      expect(Yarnlock.load(file_path)).to eq parsed_object
    end
  end

  describe '.stringify' do
    it 'stringifies correct string' do
      expect(Yarnlock.stringify(parsed_object)).to eq yarnlock
    end
  end
end
